In [1]:
import torch
from torch.nn import Linear

In [2]:
torch.manual_seed(1)

model = Linear(in_features=1, out_features=1)
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [5]:
x = torch.tensor([[0.0]])
yhat = model(x)
print(yhat)

tensor([[-0.4414]], grad_fn=<AddmmBackward0>)


In [8]:
import torch.nn as nn

class LR(nn.Module):
    def __init__(self, in_size, output_size):
        super(LR, self).__init__()
        self.linear = nn.Linear(in_size, output_size)

    def forward(self, x):
        out = self.linear(x)
        return out
    
model = LR(1, 1)
print(list(model.linear.parameters()))
x = torch.tensor([[0.0]])
yhat = model(x)
print(yhat)


[Parameter containing:
tensor([[-0.2057]], requires_grad=True), Parameter containing:
tensor([0.5087], requires_grad=True)]
tensor([[0.5087]], grad_fn=<AddmmBackward0>)


In [9]:
model.state_dict()['linear.weight'].data[0] = torch.tensor([0.5153])
model.state_dict()['linear.bias'].data[0] = torch.tensor([-0.4414])
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]
